# "service" is the name of this project. This will also be added to your AWS resource names.
service: gene-test-athena-udf-python

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11

functions:
  hello:
    handler: handler.lambda_handler

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux